os: linux
dist: bionic

language: java
jdk: openjdk8

cache:
  directories:
    - $HOME/.m2

before_install:
  - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install @openapitools/openapi-generator-cli -g

script:
  # Checking OpenAPI file
  - openapi-generator validate --input-spec stalker.yaml
  # Installing Backend
  - mvn clean install

after_success:
  # Testing Backend
  - mvn clean test coveralls:report -DrepoToken=$COVERALLSTOKEN