os: linux
dist: bionic

language: java
jdk: openjdk8

cache:
  directories:
    - $HOME/.m2

script:
  # Installing Backend
  - mvn clean compile

after_success:
  # Testing Backend
  - mvn clean test jacoco:report coveralls:report -DrepoToken=$COVERALLSTOKEN