os: linux
dist: bionic

language: java
jdk: openjdk8

cache:
  directories:
    - $HOME/.m2

script:
  # Installing Backend
  - mvn clean package -DskipTests
  - mvn test > /dev/null

after_success:
  # Testing Backend
  - mvn jacoco:report coveralls:report -DrepoToken=$COVERALLSTOKEN
