version: '3'
services:
  mysql_engine:
    container_name: stalker-rdbms
    build: ./containers/mysql-container
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_RPW}
    volumes:
      - ./containers/mysql-container/data:/var/lib/mysql
    ports:
      - "33060:3306"
  phpmyadmin:
    container_name: stalker-gui-for-rdbms
    depends_on:
      - mysql_engine
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "5000:80"
    env_file:
      - .env
    environment:
      PMA_HOST: mysql_engine
      MYSQL_ROOT_PASSWORD: ${MYSQL_RPW}
  redis_engine:
    container_name: stalker-nosql
    build: ./containers/redis-container
    ports:
      - "63800:6380"
    volumes:
      - ./containers/redis-container/data:/data
