version: '3'
services:
  mysql_engine:
    container_name: stalker-rdbms
    build: ./container
    env_file: 
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PSW}
    volumes:
      - ./container/mysql:/var/lib/mysql
    ports:
      - "33060:3306"
  phpmyadmin:
    container_name: stalker-gui-for-rdbms
    depends_on:
      - mysql_engine
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '5000:80'
    env_file: 
      - .env
    environment:
      PMA_HOST: mysql_engine
      MYSQL_ROOT_PASSWORD: ${MYSQL_PSW}