version: '3'
services:
  mysql_engine:
    container_name: stalker-rdbms
    image: mysql:8.0.20 # NON-ARM
    # image: hypriot/rpi-mysql # ARM
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_RPW}
    volumes:
      - ./containers/mysql-container/data:/var/lib/mysql
    ports:
      - "${MYSQL_PRT}:3306"
  phpmyadmin:
    container_name: stalker-gui-for-rdbms
    depends_on:
      - mysql_engine
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "5000:80"
    env_file:
      - .env
    environment:
      PMA_HOST: mysql_engine
      MYSQL_ROOT_PASSWORD: ${MYSQL_RPW}
  redis_engine:
    container_name: stalker-nosql
    image: redis:5.0.9
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "${REDIS_PRT}:6379"
    volumes:
      - ./containers/redis-container/redis.conf:/usr/local/etc/redis/redis.conf
      - ./containers/redis-container/data:/data