version: '3'
services:
  mysql_engine:
    container_name: mysql_engine
    build: ./container
    environment:
      MYSQL_ROOT_PASSWORD: $mysqlpsw
    volumes:
      - ./container/mysql:/var/lib/mysql
    ports:
      - "33060:3306"
  phpmyadmin:
    depends_on:
      - mysql_engine
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '5000:80'
    environment:
      PMA_HOST: mysql_engine
      MYSQL_ROOT_PASSWORD: $mysqlpsw
