openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Stalker API'
  description: 'API di Stalker di Imola Informatica sviluppato da qbteam'
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/qbteam/stalker-api/1.0.0
paths:
  '/organizzazioni/{organizationId}':
    get:
      tags:
      - organization
      summary: Get the information of an organization
      description: Returns a single organization
      operationId: getOrganization
      parameters:
        - name: organizationId
          in: path
          description: ID of an organization
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
            application/xml:
              schema:
                $ref: '#/components/schemas/Organization'
        '400':
          description: Invalid Id supplied
        '404':
          description: Organization not found
components:
  schemas:
    Adress:
      type: object
      properties:
        via:
          type: string
        postcode:
          type: integer
          format: int64
    Organization:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        immages:
          type: string
        adress:
          type: array
          items: 
            type: string
        serverLDAP:
          type: string
        creationDate:
          type: string
        modifyDate: 
          type: string
        perimeter:
          type: number
        trackingArea:
          type: number
        trackingMethod:
          type: number
    Place:
      type: object
      required:
        - id
        - organization
        - trackingArea
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for a place of an organization.
        name:
          type: string
          description: Name describing the place. If not set by user it gets automatically filled.
        organization:
          $ref: '#/components/schemas/Organization'
          description: >-
            Subject interested in tracking people's presence inside its own places, in either an anonymous or authenticated way.
        trackingArea:
          type: string
          description: Area subjected to movement tracking of people.
    
