openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Stalker API'
  description: 'API di Stalker di Imola Informatica sviluppato da qbteam'
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/qbteam/stalker-api/1.0.0
tags:
  - name: userAuthentication
    description: User authentication related endpoints.
  - name: adminAuthentication
    description: Administrator authentication related endpoints.
  - name: organization
    description: Organization related endpoints.
  - name: place
    description: Place related endpoints.
paths:
  '/autenticazione/login':
    post:
      tags:
        - userAuthentication
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: incorrect credentials
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationData'
  '/organization/{organizationId}':
    get:
      tags:
        - organization
      summary: Get the information of an organization
      description: Returns a single organization
      operationId: getOrganization
      parameters:
        - name: organizationId
          in: path
          description: ID of an organization
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
            application/xml:
              schema:
                $ref: '#/components/schemas/Organization'
        '400':
          description: Invalid Id supplied
        '404':
          description: Organization not found
components:
  schemas:
    AuthenticationData:
      type: object
      description: Data requested to the user when authenticating or registering to the system.
      required:
      - mail
      - password
      properties:
        mail:
          type: string
        password:
          type: string
          format: password
    AuthResponse:
      type: object
      description: Data given to the user when authenticated.
      required:
        - token
        - expirationDate
      properties:
        token:
          type: string
        expirationDate:
          type: string
          format: date-time
    Address:
      type: object
      description: The address of an organization.
      required:
        - street
        - number
        - postcode
        - city
        - country
      properties:
        street:
          type: string
        number:
          type: integer
          format: string
        postCode:
          type: integer
          format: string
        city:
          type: string
        state:
          type: string
    Organization:
      type: object
      description: >-
        Subject interested in tracking people's presence inside its own places, in either an anonymous or authenticated way.
      required:
        - id
        - name
        - address
        - creationDate
        - modifyDate
        - perimeter
        - trackingArea
        - trackingMode
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for an organization.
        name:
          type: string
          description: Name of the organization.
        description:
          type: string
          description: Small description of what the organization does.
        image:
          type: string
          description: Image/logo for the organization which gets shown on the application.
        address:
          type: array
          items:
            type: string
          $ref: '#/components/schemas/Address'
        serverLDAP:
          type: string
          description: >-
            URL or IP address of the LDAP server of the organization.
            If it's required a specific TCP port (different from LDAP's default) it must be specified.
            Needed only if trackingMethod is set to authenticated.
        creationDate:
          type: string
        modifyDate:
          format: date-time
          description: When the organization was added to the system.
        lastChangeDate:
          type: string
          format: date-time
          description: When the organization parameters were last changed.
        trackingArea:
          type: string
          description: >-
            Area subjected to movement tracking of people.
            It is a collection of (longitude, latitude) pairs consisting in a polygon.
            The string is expressed in JSON format.
        trackingMode:
          type: string
          description: How an user who added to its favorites the organization can be tracked inside the organization's trackingArea and its places.
          enum:
            - authenticated
            - anonymous
    Place:
      type: object
      description: Area of an organization subjected to tracking.
      required:
        - id
        - organization
        - trackingArea
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for a place of an organization.
        name:
          type: string
          description: Name describing the place. If not set by user it gets automatically filled.
        organizationId:
          type: integer
          format: int64
          description: Unique identifier of the organization the place is part of.
        trackingArea:
          type: string
          description: >-
            rea subjected to movement tracking of people.
            It is a collection of (longitude, latitude) pairs consisting in a polygon.
            The string is expressed in JSON format.
    User:
      type: object
      required:
        - userId
      properties:
        userId:
          type: string
          description: Authentication service's user unique identifier.
        ldapId:
          type: integer
          description: Organization LDAP server's user unique identifier.
    Administrator:
      type: object
      required:
        - administratorId
      properties:
        administratorId:
          type: string
          description: Authentication service's administrator unique identifier.
        ldapId:
          type: integer
          description: Organization LDAP server's administrator unique identifier.
    Permission:
      type: object
      description: What can or cannot do an organization's administrator.
      required:
        - userId
        - organizationId
        - permission
      properties:
        administratorId:
          type: string
          description: Authentication service's administrator unique identifier.
        organizationId:
          type: integer
          format: int64
          description: Unique identifier of the organization the administrator is part of.
        permission:
          type: string
          description: >- 
            What can or cannot do an organization's administrator.
            Owner is the highest level of permissions while viewer is the lowest.
          enum:
            - owner
            - manager
            - viewer
    Favorite:
      type: object
      description: >-
        Link between the user and the organization: only the organization which users sets to be their favorite can track their movements.
      required:
        - userId
        - organizationId
        - creationDate
      properties:
        userId:
          type: string
          description: Authentication service's user unique identifier.
        organizationId:
          type: integer
          format: int64
          description: Unique identifier of the organization the user sets as favorite.
        creationDate:
          type: string
          format: date-time
          description: When the favorite was added by the user.
    Access:
      type: object
      description: Generic access to an organization.
      required:
        - entranceTimestamp
        - exitTimestamp
      properties:
        entranceTimestamp:
          type: string
          format: date-time
          description: Date and time of the moment in which the user entered the place.
        exitTimestamp:
          type: string
          format: date-time
          description: Date and time of the moment in which the user left the place.      
    PlaceAuthenticatedAccess:
      type: object
      description: Access to a place of an organization made with the authenticated trackingMode.
      required:
        - access
        - placeId
        - ldapId
      properties:
        access:
          $ref: '#/components/schemas/Access'
        placeId:
          type: integer
          format: int64
          description: Unique identifier of the place in which the user had access.
        ldapId:
          type: integer
          format: int64
          description: Organization LDAP server's user unique identifier.
    OrganizationAuthenticatedAccess:
      type: object
      description: Access to an organization made with the authenticated trackingMode.
      required:
        - access
        - organizationId
        - ldapId
      properties:
        access:
          $ref: '#/components/schemas/Access'
        organizationId:
          type: integer
          format: int64
          description: Unique identifier of the organization in which the user had access.
        ldapId:
          type: integer
          format: int64
          description: Organization LDAP server's user unique identifier.
    PlaceAnonymousAccess:
      type: object
      description: Access to a place of an organization made with the anonymous trackingMode.
      required:
        - access
        - placeId
      properties:
        access:
          $ref: '#/components/schemas/Access'
        placeId:
          type: integer
          format: int64
          description: Unique identifier of the place in which the user had access.
    OrganizationAnonymousAccess:
      type: object
      description: Access to an organization made with the authenticated trackingMode.
      required:
        - access
        - organizationId
      properties:
        access:
          $ref: '#/components/schemas/Access'
        organizationId:
          type: integer
          format: int64
          description: Unique identifier of the organization in which the user had access.
