openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Stalker API'
  description: 'API di Stalker di Imola Informatica sviluppato da qbteam'
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/qbteam/stalker-api/1.0.0
paths:
  '/organizzazioni/{organizationId}':
    get:
      tags:
      - organization
      summary: Get the information of an organization
      description: Returns a single organization
      operationId: getOrganization
      parameters:
        - name: organizationId
          in: path
          description: ID of an organization
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
            application/xml:
              schema:
                $ref: '#/components/schemas/Organization'
        '400':
          description: Invalid Id supplied
        '404':
          description: Organization not found
components:
  schemas:
    Address:
      type: object
      description: The address of an organization.
      required:
        - street
        - number
        - postcode
        - city
        - country
      properties:
        street:
          type: string
        number:
          type: integer
          format: int32
        postCode:
          type: integer
          format: int32
        city:
          type: string
        country: 
          type: string
    Organization:
      type: object
      description: >-
        Subject interested in tracking people's presence inside its own places, in either an anonymous or authenticated way.
      required:
        - id
        - name
        - adress
        - creationDate
        - modifyDate
        - perimeter
        - trackingArea
        - trackingMethod
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for an organization.
        name:
          type: string
          description: Name of the organization.
        description:
          type: string
          description: Small description of what the organization does.
        image:
          type: string
          description: Image/logo for the organization which gets shown on the application.
        address:
          $ref: '#/components/schemas/Address'
        serverLDAP:
          type: string
          description: >-
            URL or IP address of the LDAP server of the organization.
            If it's required a specific TCP port (different from LDAP's default) it must be specified.
            Needed only if trackingMethod is set to authenticated.
        creationDate:
          type: string
          format: date-time
          description: When the organization was added to the system.
        lastChangeDate:
          type: string
          format: date-time
          description: When the organization parameters were last changed.
        trackingArea:
          type: string
          description: >-
            rea subjected to movement tracking of people.
            It is a collection of (longitude, latitude) pairs consisting in a polygon.
            The string is expressed in JSON format.
        trackingMethod:
          type: string
          description: How an user who added to its favorites the organization can be tracked inside the organization's trackingArea and its places.
          enum:
            - authenticated
            - anonymous
    Place:
      type: object
      description: Area of an organization subjected to tracking.
      required:
        - id
        - organization
        - trackingArea
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for a place of an organization.
        name:
          type: string
          description: Name describing the place. If not set by user it gets automatically filled.
        organization:
          $ref: '#/components/schemas/Organization'
        trackingArea:
          type: string
          description: >-
            rea subjected to movement tracking of people.
            It is a collection of (longitude, latitude) pairs consisting in a polygon.
            The string is expressed in JSON format.
    
